### ISSUE TITLE
Find a better way to interact with storybook from cypress

### ISSUE THREAD

**Issue by rhoffmann** [crollalowis/cl-ui#24]
maybe we can write some helper functions that allow us to easily open a section / component in the navigation tree.

also, interacting with the component is done through an iframe, maybe there is a solution to do this more easily

**Comment by rhoffmann** [comment]
or maybe we shouldn't even do e2e testing in storybook. components should be tested in isolation in the unit tests. it feels with cypress we are just testing storybook. what do you think?

**Comment by halas** [comment]
Well, indeed it seems that running cypress against storybook is a niche solution. 
Here:
https://medium.com/@mtiller/testing-react-components-using-storybook-and-cypress-1689a27f55aa
author claims he is doing it because in some niche cases testing with real dom gives different solutions. 
But maybe indeed we should run cypress only against real application and instead focus on getting here visual regression tests with screenshots, like described at then end of this article:
https://www.robinwieruch.de/visual-regression-testing-react-storybook
wdyt?

**Comment by halas** [comment]
Funnily enough, on the branch where I introduced snapshots testing:
https://github.com/crollalowis/cl-ui/pull/27
I changed structure of components, different things are shown in storybook, but test locally still passes while on travis and circle fails.

**Comment by halas** [comment]
Anyway my actionable suggestion is:
Remove cypress from this project and instead work with it on real project (co gatsby base). Are you ok with this?

**Comment by rhoffmann** [comment]
I agree with you, that we should just remove cypress.io from the component library and just use it on projects that are actually requrie e2e testing.
